name: SBOM

on:
  workflow_dispatch:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      OUTPUT: sbom.spdx
      TAG: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Kubernetes BOM
        uses: kubernetes-sigs/release-actions/setup-bom@a69972745f85aab4ba5d6c681e2a0e7f73eaff2b # v0.3.0

      - name: Generate SBOM
        run: |
          bom generate \
            --dirs=. \
            --image=enix/x509-certificate-exporter:$TAG,quay.io/enix/x509-certificate-exporter:$TAG \
            --namespace=https://github.com/enix/x509-certificate-exporter/releases/download/$TAG/$OUTPUT \
            --name="SBOM for x509-certificate-exporter version $TAG" \
            --output=$OUTPUT

      - name: Upload SBOM to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $TAG $OUTPUT
